image: ghcr.io/yardinternet/docker-php7.2-composer-image:latest

pipelines:
  custom:
    manually:
      - step:
          name: Run unit tests
          caches:
            - composer
            - vendor-directory
          script:
            - composer install --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction
            - ./vendor/bin/phpunit
  branches:
    "{master,develop}":
      - step:
          name: Run unit tests
          caches:
            - composer
            - vendor-directory
          script:
            - composer install --verbose --prefer-dist --optimize-autoloader --no-progress --no-interaction
            - ./vendor/bin/phpunit

definitions:
  caches:
    vendor-directory: vendor
